//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int Id { get; set; }
        public string BillID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> IntoMoney { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsGift { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
        public BillInfo Clone()
        {
            BillInfo bi = new BillInfo();
            bi.Id = this.Id;
            bi.BillID = this.BillID;
            bi.ProductID = this.ProductID;
            bi.ProductName = this.ProductName;
            bi.Quantity = this.Quantity;
            bi.Price = this.Price;
            bi.IntoMoney = this.IntoMoney;
            bi.Note = this.Note;
            bi.IsGift = this.IsGift;
            return bi;
        }
        public BillInfoNotNull ConvertToBINotNull()
        {
            BillInfoNotNull bi = new BillInfoNotNull();
            bi.Id = this.Id;
            bi.BillID = this.BillID;
            bi.ProductID = this.ProductID;
            bi.ProductName = this.ProductName;
            bi.Quantity = this.Quantity == null ? 0 : (int)this.Quantity;
            bi.Price = this.Price == null ? 0 : (int)this.Price;
            bi.IntoMoney = this.IntoMoney == null ? 0 : (int)this.IntoMoney;
            bi.Note = this.Note;
            bi.IsGift = this.IsGift == null ? false : true;
            return bi;
        }

    }
}
