//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillInfoes = new HashSet<BillInfo>();
            this.PromotionAndBills = new HashSet<PromotionAndBill>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<double> OriginBillValue { get; set; }
        public Nullable<double> TrueBillValue { get; set; }
        public Nullable<double> PointAdd { get; set; }
        public Nullable<int> PointSub { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsUsingAtStore { get; set; }
        public Nullable<bool> IsCusMember { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TableInfo TableInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionAndBill> PromotionAndBills { get; set; }
    }
}
