//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductApplyForPromotion
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public string PPDisplayName { get; set; }
        public Nullable<int> ProductAmount { get; set; }
        public string PromotionId { get; set; }
        public Nullable<bool> ProductType { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
