//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillInfoes = new HashSet<BillInfo>();
            this.ProductApplyForPromotions = new HashSet<ProductApplyForPromotion>();
        }
    
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> BuyValue { get; set; }
        public Nullable<int> SellValue { get; set; }
        public Nullable<int> MinimumQuantity { get; set; }
        public Nullable<int> CurrentQuantity { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string ProductImage { get; set; }
        public Nullable<bool> IsTrading { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductApplyForPromotion> ProductApplyForPromotions { get; set; }
    }
}
