//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.ProductApplyForPromotions = new HashSet<ProductApplyForPromotion>();
            this.PromotionAndBills = new HashSet<PromotionAndBill>();
        }
    
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> AmountValue { get; set; }
        public Nullable<double> PercentValue { get; set; }
        public Nullable<int> PriceBillRequire { get; set; }
        public Nullable<int> PromotionType { get; set; }
        public Nullable<bool> IsApply { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductApplyForPromotion> ProductApplyForPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionAndBill> PromotionAndBills { get; set; }
    }
}
